server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ust
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sa
    password: haha
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true